name: 🐞 Bug Report
description: File a bug report
title: "[Bug]: <title>"
labels: ["bug", "triage"]
assignees:
  - yamiM0NSTER
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we I in touch with you if I need more info?
      placeholder: ex. email@example.com, discord
    validations:
      required: false
  - type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
  - type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of software are you running?
      options:
        - 1.0.0
    validations:
      required: true
  - type: input
    id: bsversion
    attributes:
      label: What Beat Saber Version are you seeing the problem on?
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Steam
        - Oculus
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
