name: 🛠 Feature Request
description: Request a feature here, share your idea!
title: "[Feature Request]: <title>"
labels: ["enhancement"]
assignees:
  - yamiM0NSTER
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you would like to see.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can I get in touch with you if I need more info?
      placeholder: ex. email@example.com, discord
    validations:
      required: false
  - type: textarea
    attributes:
      label: Feature description
      description: A concise description of what you would expect to be added.
    validations:
      required: true
